# Site settings
title: 0x00 - NULL
description: "snutiise git blog"
baseurl: ""
url: ""

# User settings
username: snutiise
user_title: snutiise - Programmer
email: snutiise@hanmail.net
twitter_username: snutiise
github_username:  snutiise
gplus_username:  snutiise
linkedin_public_url: snutiise # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: snutiise
profile_picture: https://avatars3.githubusercontent.com/u/10993678?s=460&v=4

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about
      url: /about
      key_trigger: 5
  section_2:
    - title: facebook
      url: https://www.facebook.com/Iam.Jeon.Seung.1
      key_trigger: f
    - title: github
      url: https://github.com/snutiise
      new_tab: true
      key_trigger: g
    - title: lovelyz
      url: http://lovelyzfan.xyz
      key_trigger: l

# projects in header index
projects:
  - name: twitter crawler
    url: https://github.com/snutiise/twitter

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
